import { usePageTitle } from '../lib/usePageTitle';

export default function About() {
  usePageTitle('About');
  return (
    <div className="page-head">
      <h1>About OtherImpact</h1>
      <p className="lede">
        OtherImpact reads the news and publishes investment research theses as effect
        chains: the first-order market reaction everyone sees, then the second- and
        third-order effects the market digests more slowly. Every thesis states what
        would invalidate it, and every idea is scored publicly from publication to
        close — no edits, no survivorship bias.
      </p>
      <h3>Not investment advice</h3>
      <p>
        OtherImpact is a research and educational tool. Nothing here is a personalized
        recommendation to buy or sell any security. Ideas are generated by AI, can be
        wrong, and frequently will be — that's what the scoreboard is for. Do your own
        research and consider consulting a licensed financial adviser before investing.
      </p>
    </div>
  );
}
