import { usePageTitle } from '../lib/usePageTitle';

// Plain-language legal pages. These are sensible defaults for a research
// publication, not legal advice — have a lawyer review before charging money.

export function Terms() {
  usePageTitle('Terms of Use');
  return (
    <div className="legal">
      <h1>Terms of Use</h1>
      <p className="muted small">Last updated: July 3, 2026</p>

      <h3>What OtherImpact is</h3>
      <p>
        OtherImpact is a research and educational publication. It uses AI to read
        public news and publish analytical theses about how events might affect
        markets, together with a public record of how those theses performed.
      </p>

      <h3>Not investment advice</h3>
      <p>
        Nothing on OtherImpact is investment advice, a recommendation, or an offer
        to buy or sell any security or other instrument. Content is general and
        educational; it is not personalized to you, your finances, or your goals.
        We are not a registered investment adviser, broker, or fiduciary. If you
        need advice, consult a licensed professional.
      </p>

      <h3>AI-generated content</h3>
      <p>
        Ideas are generated by AI systems reading news sources. They can be wrong,
        outdated, or based on misreported events — and some will be. The scoreboard
        exists precisely to make that error rate visible. Past performance of
        published ideas does not predict future results.
      </p>

      <h3>Your responsibility</h3>
      <p>
        Any decision you make based on content here is yours alone. Markets involve
        risk, including total loss. To the maximum extent permitted by law,
        OtherImpact and its operators are not liable for any losses arising from
        use of this site.
      </p>

      <h3>Accounts and acceptable use</h3>
      <p>
        Features like the analyst chat require an account. Don't abuse the service:
        no scraping at disruptive volume, no attempting to extract other users'
        data, no using the chat to generate content that violates the law. We may
        suspend accounts that do.
      </p>

      <h3>Changes</h3>
      <p>
        We may update these terms as the product evolves; the date above reflects
        the latest revision. Continued use after a change means you accept it.
      </p>
    </div>
  );
}

export function Privacy() {
  usePageTitle('Privacy Policy');
  return (
    <div className="legal">
      <h1>Privacy Policy</h1>
      <p className="muted small">Last updated: July 3, 2026</p>

      <h3>What we collect</h3>
      <p>
        Browsing the research requires no account and collects no personal data
        beyond standard server logs. If you sign in (for the analyst chat), we
        store your email address and your chat history so the conversation can
        continue across sessions.
      </p>

      <h3>Where it lives</h3>
      <p>
        Data is stored with Supabase (our database and authentication provider).
        Chat messages are processed by third-party AI providers (Google, Anthropic)
        to generate responses. We do not sell your data to anyone.
      </p>

      <h3>What we don't do</h3>
      <p>
        No advertising trackers, no selling or renting personal information, no
        profiling beyond what makes the product work.
      </p>

      <h3>Your rights</h3>
      <p>
        You can request deletion of your account and associated data at any time
        by contacting us. Depending on where you live (e.g. the EU), you may have
        additional rights to access, correct, or export your data — we honor those.
      </p>

      <h3>Contact</h3>
      <p>
        Questions about this policy: contact the operator via the email listed on
        the domain registration, or the support address once published.
      </p>
    </div>
  );
}
